//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alfa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlfaDBEntities : DbContext
    {
        public AlfaDBEntities()
            : base("name=AlfaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<Notlar> Notlars { get; set; }
        public virtual DbSet<Tema> Temas { get; set; }
        public virtual DbSet<TelefonRehberi> TelefonRehberis { get; set; }
    }
}
