//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alfa
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelefonRehberi
    {
        public int RehberID { get; set; }
        public string KisiAdiSoyadi { get; set; }
        public string TelefonNumarasi { get; set; }
    }
}
